# Generated by Django 2.2.7 on 2020-11-16 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('breed', models.TextField(blank=True)),
                ('age', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Playdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True)),
                ('time', models.DateTimeField(blank=True)),
                ('owner', models.ManyToManyField(blank=True, to='project.Owner')),
                ('pet', models.ManyToManyField(blank=True, to='project.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Owner')),
                ('playdate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Playdate')),
            ],
        ),
    ]
