# Generated by Django 2.2.7 on 2020-11-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='blurb',
            field=models.TextField(blank=True),
        ),
    ]
