# Generated by Django 2.2.7 on 2020-12-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_pet_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='playdate',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
